"""initial migration

Revision ID: 3c053a85c53f
Revises: 
Create Date: 2024-12-20 17:04:58.337025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c053a85c53f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=50), nullable=False),
    sa.Column('payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_name')
    )
    op.create_table('daycare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('parent_1_name', sa.String(length=50), nullable=True),
    sa.Column('parent_1_phone', sa.String(length=15), nullable=True),
    sa.Column('parent_2_name', sa.String(length=50), nullable=True),
    sa.Column('parent_2_phone', sa.String(length=15), nullable=True),
    sa.Column('payment_mode', sa.String(length=15), nullable=True),
    sa.Column('option', sa.String(length=20), nullable=True),
    sa.Column('fee_payable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('item', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('student_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=20), nullable=True),
    sa.Column('parent1_name', sa.String(length=50), nullable=True),
    sa.Column('parent1_phone', sa.String(length=15), nullable=True),
    sa.Column('parent2_name', sa.String(length=50), nullable=True),
    sa.Column('parent2_phone', sa.String(length=15), nullable=True),
    sa.Column('fee_payable', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_participation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('student_name', sa.String(length=50), nullable=True),
    sa.Column('activity_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_paid_for', sa.Date(), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['activity_name'], ['activities.activity_name'], ),
    sa.ForeignKeyConstraint(['student_name'], ['students.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_name', 'activity_name', 'term', 'frequency', 'status', name='unique_participation')
    )
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_name'], ['students.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_activities',
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_name'], ['activities.activity_name'], ),
    sa.ForeignKeyConstraint(['student_name'], ['students.name'], ),
    sa.PrimaryKeyConstraint('student_name', 'activity_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_activities')
    op.drop_table('fees')
    op.drop_table('activity_participation')
    op.drop_table('students')
    op.drop_table('income')
    op.drop_table('expenditures')
    op.drop_table('daycare')
    op.drop_table('activities')
    # ### end Alembic commands ###
